## WEEK-1 Task Data Exploration and Cleaning
### Objective: Learn Python basics and perform basic data exploration and cleaning using Pandas.

1.Load a CSV dataset into a Pandas DataFrame. 
2.Explore data (head/tail, shape, columns, data types). 
3.Handle missing values (identify, fill/drop). 
4.Perform basic operations (filter rows, select columns). 
5.Remove duplicates. 
6.Create a derived column (total_amount = price * quantity). 
7.Save the cleaned dataset as a new CSV file. Output: Jupyter Notebook (.ipynb) + cleaned CSV + brief summary."

### 1. Loading our CSV dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('raw_data/Combined_dataset.csv')
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

Dataset loaded successfully

### 2.Explore data (head/tail, shape, columns, data types).

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
df.shape

(1000, 24)

In [6]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [7]:
df.columns.tolist()

['product_id',
 'title',
 'product_description',
 'rating',
 'ratings_count',
 'initial_price',
 'discount',
 'final_price',
 'currency',
 'images',
 'delivery_options',
 'product_details',
 'breadcrumbs',
 'product_specifications',
 'amount_of_stars',
 'what_customers_said',
 'seller_name',
 'sizes',
 'videos',
 'seller_information',
 'variations',
 'best_offer',
 'more_offers',
 'category']

In [8]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

### 3.Handle missing values (identify, fill/drop).

In [10]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

I can observe that a very huge amount of data in columns like "videos" and "variation" is missing/is null and they won't contribute much in the Data Science model 
So I have decided to drop these columns
And for other columns:
1. discount: I will put zero with assumption that there is no discount for those products.
2. similarly for other columns I will replace NaN with values like 0,"unknown".

In [11]:
df_cleaned=df.copy()

In [12]:
df_cleaned.drop(columns=["videos","variations"],inplace=True)

In [13]:
df_cleaned["discount"]=df["discount"].fillna(0)
df_cleaned["what_customers_said"]=df["what_customers_said"].fillna("No review available")
df_cleaned["seller_name"]=df["seller_name"].fillna("Unknown")
df_cleaned["seller_information"]=df["seller_information"].fillna("Not available")

In [14]:
df_cleaned.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
dtype: int64

As we can see I have handled all the missing values.
Also I have filled the necessary columns with appropriate values.

### 4.Perform basic operations (filter rows, select columns)

#### Selecting columns

In [15]:
df_cleaned.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category'],
      dtype='object')

In [16]:
df_cleaned[["title","initial_price","final_price","rating"]]

              title  initial_price   final_price  rating
0       Lino Perros           3995   "₹3,995.00"     3.8
1    Tommy Hilfiger           2899   "₹2,899.00"     4.5
2             Lavie           2999   "₹2,999.00"     4.4
3            F Gear           1675   "₹1,675.00"     4.4
4         MYTRIDENT           2899   "₹2,899.00"     4.7
..              ...            ...           ...     ...
995           KREDO          11890  "₹11,890.00"     3.5
996           GUESS           8900   "₹8,900.00"     5.0
997        GIORDANO           7950   "₹7,950.00"     2.8
998        Fastrack           3295   "₹2,636.00"     4.3
999         BOLDFIT            699     "₹699.00"     3.8

[1000 rows x 4 columns]

In [17]:
df_cleaned.loc[5:10 ,["title","initial_price","rating"]]

         title  initial_price  rating
5          H&M           1399     4.5
6   AVI Living           1399     4.0
7      My Room           2999     4.7
8      My Room           2999     4.5
9   Story@home           2199     3.7
10   MYTRIDENT           2199     4.4

### Selecting rows

In [18]:
print(df_cleaned.loc[777,"title"])

Sztori

In [19]:
df_cleaned.loc[500:510]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
500,17288460,Cutiekins,Girls Off White Solid Knitted Linen Palazzos,4.2,26,1099,59.0,"""₹450.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":1,""2_stars"":3,""3_stars"":0,""4_stars"":...",No review available,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""19.0in"",""value_name"":...","A-2███, T███D F█████████ -1█████████████████████8","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
501,17307462,Clora Creation,Women Pack Of 2 Red & Beige Knitted Ethnic Pal...,0.0,0,2399,59.0,"""₹983.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Clo███Cre███on,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",C-1███ Ba███ent█████████Col███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
502,17309774,Clora Creation,Women Pack Of 2 Navy Blue & White Knitted Pala...,3.8,6,1999,60.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",No review available,Clo███Cre███on,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",C-1███ Ba███ent█████████Col███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
503,15114984,Go Colors,Women White Ethnic Palazzos,4.0,53,899,0.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":8,""2_stars"":2,""3_stars"":1,""4_stars"":...",No review available,GO ███HIO███IND█████████ED,"[{""size"":""30"",""value"":""31.0in"",""value_name"":""G...",8/6███ A ███ La█████████eri███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
504,15782402,BEARDO,Beardo Set of God Father & Dark Side Eau De Pa...,4.4,153,2700,68.0,"""₹864.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Personal Care"",""url"":""https://www.my...","[{""specification_name"":""Fragrance"",""specificat...","{""1_star"":8,""2_stars"":2,""3_stars"":9,""4_stars"":...",No review available,Omn███ch ███ail███,"[{""size"":""Pack""}]","11t███loo███Fla█████████6, ███████████████████...","{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",perfume-and-body-mist
505,15715190,Salona Bichona,Set Of 2 White & Pink Floral Printed Pure Cott...,3.7,12,499,50.0,"""₹249.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Print or Pattern Type""...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No review available,SAL███ BI███NA █████████DIA██████████████████,"[{""size"":""Onesize""}]","G-1███82,███ASE█████████APU███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",pillow-covers
506,15720606,Rubans,Gold-Plated Contemporary Boho Finger Ring,3.5,6,1890,74.0,"""₹415.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,AK ███erp███es,"[{""size"":""Onesize""}]",Plo███o 2███ 4t█████████ast███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ring
507,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",No review available,ZAV███ PE███S,"[{""size"":""Onesize""}]","12,███T F███R, █████████LDG███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
508,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",No review available,Unknown,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring
509,10601120,Saral Home,Green Solid Anti Slip Polyester Kitchen Runner,0.0,0,2499,27.0,"""₹1,824.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Material"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,SAR███HOM███ASY█████████RIV████████████,"[{""size"":""Onesize""}]",NEA███LOR███SEC█████████RT ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",runners
510,10018911,SEJ by Nisha Gupta,Multicoloured Printed Table Runner,4.5,13,1849,70.0,"""₹554.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Material"",""specificati...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,SEJ███RNI███NGS█████████LIM██████,"[{""size"":""Onesize""}]",K-1███ST ███OR █████████AGA███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",runners

In [20]:
df_cleaned.iloc[500:510]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
500,17288460,Cutiekins,Girls Off White Solid Knitted Linen Palazzos,4.2,26,1099,59.0,"""₹450.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":1,""2_stars"":3,""3_stars"":0,""4_stars"":...",No review available,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""19.0in"",""value_name"":...","A-2███, T███D F█████████ -1█████████████████████8","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
501,17307462,Clora Creation,Women Pack Of 2 Red & Beige Knitted Ethnic Pal...,0.0,0,2399,59.0,"""₹983.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Clo███Cre███on,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",C-1███ Ba███ent█████████Col███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
502,17309774,Clora Creation,Women Pack Of 2 Navy Blue & White Knitted Pala...,3.8,6,1999,60.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",No review available,Clo███Cre███on,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",C-1███ Ba███ent█████████Col███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
503,15114984,Go Colors,Women White Ethnic Palazzos,4.0,53,899,0.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":8,""2_stars"":2,""3_stars"":1,""4_stars"":...",No review available,GO ███HIO███IND█████████ED,"[{""size"":""30"",""value"":""31.0in"",""value_name"":""G...",8/6███ A ███ La█████████eri███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos
504,15782402,BEARDO,Beardo Set of God Father & Dark Side Eau De Pa...,4.4,153,2700,68.0,"""₹864.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Personal Care"",""url"":""https://www.my...","[{""specification_name"":""Fragrance"",""specificat...","{""1_star"":8,""2_stars"":2,""3_stars"":9,""4_stars"":...",No review available,Omn███ch ███ail███,"[{""size"":""Pack""}]","11t███loo███Fla█████████6, ███████████████████...","{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",perfume-and-body-mist
505,15715190,Salona Bichona,Set Of 2 White & Pink Floral Printed Pure Cott...,3.7,12,499,50.0,"""₹249.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Print or Pattern Type""...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No review available,SAL███ BI███NA █████████DIA██████████████████,"[{""size"":""Onesize""}]","G-1███82,███ASE█████████APU███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",pillow-covers
506,15720606,Rubans,Gold-Plated Contemporary Boho Finger Ring,3.5,6,1890,74.0,"""₹415.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,AK ███erp███es,"[{""size"":""Onesize""}]",Plo███o 2███ 4t█████████ast███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ring
507,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",No review available,ZAV███ PE███S,"[{""size"":""Onesize""}]","12,███T F███R, █████████LDG███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
508,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",No review available,Unknown,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring
509,10601120,Saral Home,Green Solid Anti Slip Polyester Kitchen Runner,0.0,0,2499,27.0,"""₹1,824.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Material"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,SAR███HOM███ASY█████████RIV████████████,"[{""size"":""Onesize""}]",NEA███LOR███SEC█████████RT ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",runners

In [21]:
#Highly rated products:
df_cleaned[df_cleaned["rating"]>4.8]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"[{""name"":""Footwear"",""url"":""https://www.myntra....","[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",SAI███USE███OT █████████ NA███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
44,21850852,Soie,Women High Waist Full Coverage Lace Brief,4.9,14,390,5.0,"""₹370.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,GIN███IND███RIE█████████,"[{""size"":""S"",""value"":""26.4in to 28.7in"",""value...",Plo███o B███9-3█████████oor███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
48,22196594,Zoiro,Men Pack Of 2 Anti-Bacterial Basic Briefs,5.0,6,499,0.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",J.G███OSI███ PR█████████ITE███,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",58/███15 ███AMP█████████LIP███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
52,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888,65.0,"""₹310.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",A-2███NOI███SEC█████████AUT███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
88,16185546,ellementry,Gold-Toned 2 Pieces Stainless Steel Matte Spoon,5.0,5,1750,0.0,"""₹1,750.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Material"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Dil███ Es███tia█████████d,"[{""size"":""Onesize""}]",Vil███e C███ota█████████ayr███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",cutlery
155,20046216,YK Disney,Girls Minnie Mouse Graphic Printed A-Line T-sh...,5.0,7,999,67.0,"""₹329.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,CRO███OAD███LOT█████████LTD███,"[{""size"":""2-3Y"",""value"":""23.0in"",""value_name"":...",75/███eer███gar█████████ Ha███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
178,13449506,DOOR74,Women Black Solid Maxi Dress,5.0,7,2399,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,JXP███S,"[{""size"":""S"",""value"":""7.0in"",""value_name"":""Sle...",D74███D F███ANE█████████Noi███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
207,15014966,Priyaasi,Gold-Toned & Gold Plated Contemporary Jhumkas ...,4.9,13,3949,76.0,"""₹947.00""",INR,http://assets.myntassets.com/assets/images/150...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]",PRI███DES███S P█████████MIT███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
239,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",1st███oor███ - █████████R -███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
326,13359482,FLYING BERRY,Silver-Toned Solid Handheld Bag,4.9,7,2999,44.0,"""₹1,679.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Abh███Ove███as ██████,"[{""size"":""Onesize""}]",A42███nd ███orO█████████str███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
334,17647418,FOOTONS,Women Beige Comfort Sandals,5.0,2,3199,55.0,"""₹3,199.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Footwear"",""url"":""https://www.myntra....","[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""36"",""value"":""21.0cm"",""value_name"":""T...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
386,19008496,Calvin Klein Jeans,Women Skinny Fit High-Rise Light Fade Stretcha...,5.0,8,7999,40.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Pla███um ███hio███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1ST███OOR███O 5█████████MAH███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
437,22110424,VASTRADO,Ethnic Motifs Printed Mandarin Collar Pure Cot...,5.0,2,1199,55.0,"""₹539.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,CRE███VE ███MEN█████████E L█████████,"[{""size"":""XS"",""value"":""40.2in"",""value_name"":""C...",G11███11-███-11█████████-11███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",kurtas
485,17832728,Dreamz by Pantaloons,Typography Printed T-shirt Nightdress,4.9,12,699,47.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/178...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Unknown,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",nightdress
547,15880308,Sirona,Aloevera Post Shave Gel & Twin Blade Disposabl...,4.9,7,294,3.0,"""₹285.00""",INR,http://assets.myntassets.com/assets/images/158...,...,"[{""name"":""Personal Care"",""url"":""https://www.my...","[{""specification_name"":""Formulation"",""specific...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Sir███ Hy███ne █████████imi██████,"[{""size"":""80-100 ML""}]","Plo███o.3███ Fi█████████,10███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shaving-essentials
558,18996772,U.S. Polo Assn.,U S Polo Assn Men Coral and Blue Striped 100% ...,4.9,10,2799,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Tight""}...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",10T███LOO███DU █████████ITY███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
658,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",180███ Bh███ Wa█████████ Co███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
721,16864474,Puma,Men Orange & White Spike 22.2 Cricket Shoes,5.0,3,6999,20.0,"""₹5,599.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""name"":""Footwear"",""url"":""https://www.myntra....","[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Pum███por███Ind█████████td.█████████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Pum███por███Ind█████████d/ ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
840,18854764,KAMI KUBI,Olive Green Striped Top,5.0,4,1299,62.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""T...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
876,8365569,Nun,Women Navy Blue & White Printed Crop A-Line Top,4.9,14,1495,70.0,"""₹1,495.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
881,9557519,MANGO,Women Yellow Self Design Top,5.0,1,2490,35.0,"""₹2,490.00""",INR,http://assets.myntassets.com/assets/images/955...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
914,18670518,max,Girls Pink & White Regular Fit Printed Pure Co...,4.9,8,599,20.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Unknown,"[{""size"":""2-3Y"",""value"":""20.0in"",""value_name"":...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",track-pants
917,18537496,Bannos Swagger,Women Grey Solid Joggers,5.0,5,1699,76.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Unknown,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",track-pants
958,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ray███d L███ted███,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...","RAY███D L███TED█████████, P███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]","Fla███o. ███, 6█████████y C███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Unknown,"[{""size"":""Onesize""}]",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [22]:
#Highly rated watches
df_cleaned[(df_cleaned["rating"]>4.5) & (df_cleaned["category"]=="watches")]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]","Fla███o. ███, 6█████████y C███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No review available,Fla███ech███tai███,"[{""size"":""Onesize""}]","3rd███165███th █████████, s███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Unknown,"[{""size"":""Onesize""}]",Not available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [23]:
#Converting string prices to float prices 
df_cleaned["final_price"] = (
    df_cleaned["final_price"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False).str.strip().astype(float)
)

In [24]:
df_cleaned["final_price"]

0       3995.0
1       2899.0
2       2999.0
3       1675.0
4       2899.0
        ...
995    11890.0
996     8900.0
997     7950.0
998     2636.0
999      699.0
Name: final_price, Length: 1000, dtype: float64

In [25]:
#Accessing rows with category as Jeans and price <1000
df_cleaned[(df_cleaned['category'] == 'jeans') & (df_cleaned['final_price'] < 1000)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
378,18873126,KETCH,Men Charcoal Slim Fit Clean Look Light Fade St...,4.0,20,1749,64.0,629.0,INR,http://assets.myntassets.com/assets/images/188...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
379,18826658,Chemistry,Women Navy Blue Casual Jeans,3.7,15,1899,55.0,854.0,INR,http://assets.myntassets.com/assets/images/188...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":4,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,Che███try███sig█████████ Li██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","God███ No███,8,█████████ldi███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
387,18873142,KETCH,Men Blue Slim Fit Low Distress Heavy Fade Stre...,0.0,0,1849,62.0,699.0,INR,http://assets.myntassets.com/assets/images/188...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",S &███Mar███ing███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...","Sy ███330███324█████████B,3███████████████████...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
390,18979610,KiddoPanti,Girls Grey No Fade Stretchable Cotton Jeans,3.9,7,1399,52.0,671.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No review available,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""19.6in"",""value_name"":...","Gro███ Fl███, 4█████████n A███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
401,18953840,KETCH,Men Grey Slim Fit Heavy Fade Stretchable Jeans,3.2,24,1899,68.0,607.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":4,""2_stars"":3,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
403,18953870,KETCH,Men Charcoal Tapered Fit Light Fade Stretchabl...,3.8,85,1749,62.0,682.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":12,""2_stars"":5,""3_stars"":10,""4_stars...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
405,18925586,KETCH,Men Charcoal Skinny Fit Mildly Distressed Stre...,3.6,15,1749,62.0,649.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",No review available,S &███Mar███ing███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...","Sy ███330███324█████████B,3███████████████████...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
415,18925582,KETCH,Men Blue Bootcut Mildly Distressed Heavy Fade ...,2.9,11,1999,62.0,739.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":4,""3_stars"":1,""4_stars"":...",No review available,Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
419,18708638,Dennis Lingo,Men Black Slim Fit Low Distress Light Fade Str...,3.4,13,3199,73.0,863.0,INR,http://assets.myntassets.com/assets/images/187...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":4,""2_stars"":0,""3_stars"":2,""4_stars"":...",No review available,Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",2nd███oor███O. █████████Lan███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
422,21184968,HERE&NOW,Women Flared Heavy Fade Stretchable Jeans,4.6,111,2399,68.0,767.0,INR,http://assets.myntassets.com/assets/images/211...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","11t███loo███Fla█████████6, ███████████████████...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
429,18734132,Flying Machine,Men Blue Jackson Skinny Fit Low-Rise Heavy Fad...,3.6,62,2499,61.0,974.0,INR,http://assets.myntassets.com/assets/images/187...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":13,""2_stars"":2,""3_stars"":9,""4_stars""...",No review available,ARV███ LI███TYL█████████LIM██████,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",10T███LOO███DU █████████ITY███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans

In [26]:
#Accessing high rated products and price<500
df_cleaned[(df_cleaned["rating"]>4.5) & (df_cleaned['final_price'] < 500)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,0.0,345.0,INR,http://assets.myntassets.com/assets/images/186...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Back"",""specification_v...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",VI/███ AB███ ST█████████ODE███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
44,21850852,Soie,Women High Waist Full Coverage Lace Brief,4.9,14,390,5.0,370.0,INR,http://assets.myntassets.com/assets/images/218...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,GIN███IND███RIE█████████,"[{""size"":""S"",""value"":""26.4in to 28.7in"",""value...",Plo███o B███9-3█████████oor███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
48,22196594,Zoiro,Men Pack Of 2 Anti-Bacterial Basic Briefs,5.0,6,499,0.0,499.0,INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",J.G███OSI███ PR█████████ITE███,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",58/███15 ███AMP█████████LIP███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
49,22196914,Zivame,Women Pack Of 3 Low-Rise Ultra Soft Bikini Briefs,4.6,5,799,50.0,399.0,INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,MIL███AR ███AIL█████████LIM██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",MIL███TAR███TAI█████████ LI███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
50,21906602,bummer,Women Printed Micro Modal Mid Rise Boy Shorts,4.6,23,599,25.0,449.0,INR,http://assets.myntassets.com/assets/images/219...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,BAL███APP███LS █████████IMI██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...","201███WAR███H, █████████TEL███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
52,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888,65.0,310.0,INR,http://assets.myntassets.com/assets/images/224...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",A-2███NOI███SEC█████████AUT███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
54,18882294,VStar,Women White Solid Modern Fit Deep Neckline Ca...,4.8,10,265,0.0,265.0,INR,http://assets.myntassets.com/assets/images/188...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,V S███ CR███ION█████████,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""T...",VI/███ AB███ ST█████████ODE███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",camisoles
128,17692718,Style Quotient,Women Tranquil Teal Solid Halter Neck Dress,4.8,8,1599,69.0,495.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
155,20046216,YK Disney,Girls Minnie Mouse Graphic Printed A-Line T-sh...,5.0,7,999,67.0,329.0,INR,http://assets.myntassets.com/assets/images/200...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,CRO███OAD███LOT█████████LTD███,"[{""size"":""2-3Y"",""value"":""23.0in"",""value_name"":...",75/███eer███gar█████████ Ha███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
169,13406942,Global Desi,Girls Blue Embroidered A-Line Denim Dress,4.8,8,1799,75.0,449.0,INR,http://assets.myntassets.com/assets/images/134...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,OCH███AND███ACK█████████LIM██████,"[{""size"":""3-4Y"",""value"":""21.0in"",""value_name"":...",Bui███ng ███rat█████████eam███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
202,12999996,Vishudh,Women Navy Blue Checked Dupatta,4.6,17,599,62.0,227.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Border"",""specification...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",No review available,Fla███tar███mme██████,"[{""size"":""Onesize""}]","1st███oor███abi█████████02,███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dupatta
260,12926546,natural vibes,Unisex Ayurvedic Teatree Facewash 150ml,4.8,9,449,5.0,426.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Personal Care"",""url"":""https://www.my...","[{""specification_name"":""Collection Name"",""spec...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,TRA███LA ███OM █████████,"[{""size"":""125-150 ML""}]","C7 ███T N███29,█████████RLD███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",face-wash-and-cleanser
489,15973760,Zoom Minimondo,Unisex Kids Magenta & Blue Pure Cotton Night suit,4.8,10,1299,69.0,402.0,INR,http://assets.myntassets.com/assets/images/159...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,KCJ███RKE███G P█████████MIT███,"[{""size"":""7-8Y"",""value"":""34.0in"",""value_name"":...",SAD███D D███AVA█████████OP ███████████████████...,"{""applicable_on"":""Orders above Rs. 599 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",night-suits
547,15880308,Sirona,Aloevera Post Shave Gel & Twin Blade Disposabl...,4.9,7,294,3.0,285.0,INR,http://assets.myntassets.com/assets/images/158...,...,"[{""name"":""Personal Care"",""url"":""https://www.my...","[{""specification_name"":""Formulation"",""specific...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,Sir███ Hy███ne █████████imi██████,"[{""size"":""80-100 ML""}]","Plo███o.3███ Fi█████████,10███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shaving-essentials

### 5.Remove duplicates

In [27]:
print(df_cleaned.duplicated().sum())

0

In [28]:
 print(df_cleaned['product_id'].duplicated().sum())

0

In [29]:
print(df_cleaned['product_id'].nunique())

1000

In [30]:
print(df_cleaned.duplicated(subset=["product_id"]).sum())

0

As you can see this dataset doesn't contains any duplicates so I am procedding further
But when I execute the cell below I find the result as follows:

In [31]:
df_cleaned[df_cleaned.duplicated(subset=['product_description', 'seller_name', 'initial_price'], keep=False)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
199,22601148,Nimidiya,Dupatta With taping Border,3.3,3,999,60.0,399.0,INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Border"",""specification...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No review available,PRE███TI ███LEC██████,"[{""size"":""Onesize""}]","10,███rac███ ro█████████ GU███████████████","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dupatta
200,22601132,Nimidiya,Dupatta With taping Border,3.2,9,999,60.0,399.0,INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Border"",""specification...","{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...",No review available,PRE███TI ███LEC██████,"[{""size"":""Onesize""}]","10,███rac███ ro█████████ GU███████████████","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dupatta
374,18973692,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.2,426,4099,57.0,4099.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":44,""2_stars"":12,""3_stars"":26,""4_star...","[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
389,18973922,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.1,237,4099,0.0,4099.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":22,""2_stars"":8,""3_stars"":27,""4_stars...","[{""percentage"":""39"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans

Since the product ID is different so this tells me that the product differs and it is not duplicate
But If my organisation tells me to consider it as a duplicate and get rid of these duplicates, I can remove this simply by using drop_duplicates()

### 6. Create a derived column (total_amount = price * quantity)

Since my dataset doesn't contains any column like quantity
therefore the total amount would be same as final_price

#### i.e. total_amount == final_price

So, In order to attempt this question I will add a "quantity" column and I will fill random int values in that column between range (1,3) 3 inclusive, so I can stimulate the total_amount

In [32]:
np.random.seed(42)  
df_cleaned['quantity'] = np.random.randint(1, 4, size=len(df_cleaned))
df_cleaned['quantity'].head()

0    3
1    1
2    3
3    3
4    1
Name: quantity, dtype: int32

In [33]:
df_cleaned["total_amount"]=df_cleaned["quantity"]*df_cleaned["final_price"]
df_cleaned[["final_price","quantity","total_amount"]].head(10)

   final_price  quantity  total_amount
0       3995.0         3       11985.0
1       2899.0         1        2899.0
2       2999.0         3        8997.0
3       1675.0         3        5025.0
4       2899.0         1        2899.0
5       1399.0         1        1399.0
6       1399.0         3        4197.0
7       2999.0         2        5998.0
8       2999.0         3        8997.0
9       2199.0         3        6597.0

In [34]:
df_cleaned.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category', 'quantity', 'total_amount'],
      dtype='object')

In [35]:
df_cleaned["total_amount"].describe()

count     1000.000000
mean      3353.762000
std       4066.935451
min        199.000000
25%       1118.250000
50%       1995.000000
75%       3999.000000
max      53985.000000
Name: total_amount, dtype: float64

We can see I have successfully added total_amount columns for simulation purpose

### 7.Save the cleaned dataset as a new CSV file.

In [36]:
df_cleaned.to_csv('processed_data/Combined_dataset_cleaned.csv', index=False)