In [1]:
import getpass
import pandas as pd
from sqlalchemy import create_engine

password = getpass.getpass("MySQL password: ")
engine = create_engine(f"mysql+mysqlconnector://root:{password}@localhost/Superstore")

%load_ext sql
%sql mysql+mysqlconnector://root:{password}@localhost/Superstore
%config SqlMagic.autocommit = True
%config SqlMagic.autopandas = True

print("Connected to superstore database")

MySQL password:  ········

Connected to superstore database

## Step 1: Setup Data

### 1. Import the Superstore dataset into a table named superstore_raw.

In [2]:
df = pd.read_csv('Superstore.csv', encoding='latin1')
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed').dt.strftime('%Y-%m-%d')
df['ship_date'] = pd.to_datetime(df['ship_date'], format='mixed').dt.strftime('%Y-%m-%d')

In [3]:
df.to_sql('superstore_raw', con=engine, if_exists='replace', index=False)

9994

In [4]:
print(f"Loaded {len(df)} rows into superstore_raw")

Loaded 9994 rows into superstore_raw

### 2. Create these 3 tables from it:  
1.customers  
2.orders  
3.products

In [5]:
%%sql

CREATE TABLE customers (
    customer_id   VARCHAR(50)  PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL
);

 * mysql+mysqlconnector://root:***@localhost/Superstore
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

CREATE TABLE products (
    product_id    VARCHAR(50)  PRIMARY KEY,
    product_name  VARCHAR(255) NOT NULL,
    category      VARCHAR(100),
    sub_category  VARCHAR(100)
);

 * mysql+mysqlconnector://root:***@localhost/Superstore
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

CREATE TABLE IF NOT EXISTS orders (
    order_item_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id      VARCHAR(50)  NOT NULL,
    customer_id   VARCHAR(50)  NOT NULL,
    product_id    VARCHAR(50)  NOT NULL,
    order_date    DATE         NOT NULL,
    sales         DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

 * mysql+mysqlconnector://root:***@localhost/Superstore
0 rows affected.

Empty DataFrame
Columns: []
Index: []

### 3. Insert data into these tables using SELECT DISTINCT.

In [10]:
%%sql

INSERT INTO customers (customer_id, customer_name)
SELECT DISTINCT customer_id, customer_name
FROM superstore_raw;

 * mysql+mysqlconnector://root:***@localhost/Superstore
793 rows affected.

Empty DataFrame
Columns: []
Index: []

In [11]:
%%sql

INSERT INTO products (product_id, product_name, category, sub_category)
SELECT product_id, MAX(product_name), MAX(category), MAX(sub_category)
FROM superstore_raw
GROUP BY product_id;

 * mysql+mysqlconnector://root:***@localhost/Superstore
1862 rows affected.

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql

INSERT INTO orders (order_id, customer_id, product_id, order_date, sales)
SELECT order_id, customer_id, product_id, order_date, sales
FROM superstore_raw;

 * mysql+mysqlconnector://root:***@localhost/Superstore
9994 rows affected.

Empty DataFrame
Columns: []
Index: []

In [13]:
%%sql

SELECT 'customers' AS table_name, COUNT(*) AS row_count FROM customers
UNION ALL
SELECT 'products',COUNT(*) FROM products
UNION ALL
SELECT 'orders', COUNT(*) FROM orders;

 * mysql+mysqlconnector://root:***@localhost/Superstore
3 rows affected.

  table_name  row_count
0  customers        793
1   products       1862
2     orders       9994

## Step 2: Perform Required Queries

### 1. Find all orders where sales are greater than the average sales. (Subquery)

In [57]:
%%sql

SELECT order_id, customer_id, product_id, sales
FROM orders
WHERE sales > (SELECT AVG(sales) FROM orders);

 * mysql+mysqlconnector://root:***@localhost/Superstore
2360 rows affected.

            order_id customer_id       product_id    sales
0     CA-2016-152156    CG-12520  FUR-BO-10001798   261.96
1     CA-2016-152156    CG-12520  FUR-CH-10000454   731.94
2     US-2015-108966    SO-20335  FUR-TA-10000577   957.58
3     CA-2014-115812    BH-11710  TEC-PH-10002275   907.15
4     CA-2014-115812    BH-11710  FUR-TA-10001539  1706.18
...              ...         ...              ...      ...
2355  US-2016-103674    AP-10720  TEC-PH-10004080   271.96
2356  US-2016-103674    AP-10720  TEC-PH-10002496   249.58
2357  US-2016-103674    AP-10720  OFF-BI-10002026   437.47
2358  CA-2017-121258    DB-13060  TEC-PH-10003645   258.58
2359  CA-2017-119914    CC-12220  OFF-AP-10002684   243.16

[2360 rows x 4 columns]

### 2. Find the highest sales order for each customer. (Subquery)

In [58]:
%%sql
SELECT o1.customer_id, o1.order_id, o1.sales
FROM orders o1
WHERE o1.sales = (
    SELECT MAX(o2.sales) FROM orders o2
    WHERE o2.customer_id = o1.customer_id
);

 * mysql+mysqlconnector://root:***@localhost/Superstore
795 rows affected.

    customer_id        order_id    sales
0      CG-12520  CA-2016-152156   731.94
1      SO-20335  US-2015-108966   957.58
2      BH-11710  CA-2014-115812  1706.18
3      EB-13870  CA-2015-106320  1044.63
4      TB-21520  US-2015-150630  3083.43
..          ...             ...      ...
790    DH-13075  CA-2015-159534  1087.94
791    IM-15055  CA-2016-129630  2799.96
792    HW-14935  CA-2017-121559  2405.20
793    RB-19435  CA-2017-153871   735.98
794    AP-10720  US-2016-103674   437.47

[795 rows x 3 columns]

### 3. Calculate total sales for each customer. (CTE)

In [59]:
%%sql

WITH customer_sales AS (
    SELECT customer_id, SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT c.customer_name, cs.total_sales
FROM customer_sales cs
JOIN customers c ON cs.customer_id = c.customer_id;

 * mysql+mysqlconnector://root:***@localhost/Superstore
793 rows affected.

          customer_name total_sales
0            Alex Avila     5563.56
1          Allen Armold     1056.39
2          Andrew Allen     1790.51
3         Anna Andreadi     5086.94
4         Aaron Bergman      886.15
..                  ...         ...
788        Xylona Preis     2374.66
789      Yoseph Carroll     5454.35
790       Yana Sorensen     6720.44
791    Zuschuss Carroll     8025.70
792  Zuschuss Donatelli     1493.94

[793 rows x 2 columns]

### 4. Find customers whose total sales are above average. (CTE + Subquery)

In [60]:
%%sql
WITH customer_sales AS (
    SELECT customer_id, ROUND(SUM(sales), 2) AS total_sales
    FROM   orders
    GROUP BY customer_id
)
SELECT customer_id, total_sales
FROM customer_sales
WHERE total_sales > (SELECT AVG(total_sales) FROM customer_sales)
ORDER BY total_sales DESC;

 * mysql+mysqlconnector://root:***@localhost/Superstore
294 rows affected.

    customer_id total_sales
0      SM-20320    25043.07
1      TC-20980    19052.22
2      RB-19360    15117.35
3      TA-21385    14595.62
4      AB-10105    14473.57
..          ...         ...
289    JK-16120     2932.49
290    SW-20455     2921.54
291    ML-17410     2921.51
292    RD-19585     2912.90
293    CY-12745     2900.02

[294 rows x 2 columns]

### 5. Rank all customers based on total sales. (Window Function)

In [61]:
%%sql

SELECT customer_id,
       ROUND(SUM(sales), 2) AS total_sales,
       RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM orders
GROUP BY customer_id
ORDER BY sales_rank;

 * mysql+mysqlconnector://root:***@localhost/Superstore
793 rows affected.

    customer_id total_sales  sales_rank
0      SM-20320    25043.07           1
1      TC-20980    19052.22           2
2      RB-19360    15117.35           3
3      TA-21385    14595.62           4
4      AB-10105    14473.57           5
..          ...         ...         ...
788    RS-19870       22.33         789
789    MG-18205       16.74         790
790    CJ-11875       16.52         791
791    LD-16855        5.30         792
792    TS-21085        4.84         793

[793 rows x 3 columns]

In [62]:
### 6. Assign row numbers to each order within a customer. (Window Function + PARTITION BY)

In [63]:
%%sql
SELECT customer_id, order_id, order_date, sales,
       ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date ASC, order_id ASC) AS order_sequence
FROM orders;

 * mysql+mysqlconnector://root:***@localhost/Superstore
9994 rows affected.

     customer_id        order_id  order_date   sales  order_sequence
0       AA-10315  CA-2014-128055  2014-03-31   52.98               1
1       AA-10315  CA-2014-128055  2014-03-31  673.57               2
2       AA-10315  CA-2014-138100  2014-09-15   14.56               3
3       AA-10315  CA-2014-138100  2014-09-15   14.94               4
4       AA-10315  CA-2015-121391  2015-10-04   26.96               5
...          ...             ...         ...     ...             ...
9989    ZD-21925  CA-2016-167682  2016-04-03  259.96               5
9990    ZD-21925  US-2016-147991  2016-05-05   16.72               6
9991    ZD-21925  CA-2016-152471  2016-07-08  823.96               7
9992    ZD-21925  CA-2016-152471  2016-07-08   15.98               8
9993    ZD-21925  CA-2017-141481  2017-06-11   61.44               9

[9994 rows x 5 columns]

### 7. Display top 3 customers based on total sales. (Window Function)

In [64]:
%%sql
SELECT customer_id, total_sales,sales_rank
FROM (
    SELECT customer_id ,ROUND(SUM(sales), 2) AS total_sales,RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
    FROM orders
    GROUP BY customer_id
)
ranked
WHERE sales_rank <= 3;

 * mysql+mysqlconnector://root:***@localhost/Superstore
3 rows affected.

  customer_id total_sales  sales_rank
0    SM-20320    25043.07           1
1    TC-20980    19052.22           2
2    RB-19360    15117.35           3

In [65]:
%%sql
WITH ranked_customers AS (
    SELECT customer_id, 
           SUM(sales) AS total_sales,
           RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
    FROM orders
    GROUP BY customer_id
)
SELECT c.customer_name, rc.total_sales, rc.sales_rank
FROM ranked_customers rc
JOIN customers c ON rc.customer_id = c.customer_id
WHERE rc.sales_rank <= 3;

 * mysql+mysqlconnector://root:***@localhost/Superstore
3 rows affected.

  customer_name total_sales  sales_rank
0   Sean Miller    25043.07           1
1  Tamara Chand    19052.22           2
2  Raymond Buch    15117.35           3

### Step 3: Final Combined Query

#### Write one final query that shows: 
- Customer Name  
- Total Sales  
- Rank  
(Use JOIN + CTE + Window Function together)

In [66]:
%%sql

WITH customer_sales AS (
    SELECT o.customer_id,ROUND(SUM(o.sales), 2) AS total_sales
    FROM   orders o
    GROUP BY o.customer_id
),
customer_ranked AS (
    SELECT cs.customer_id,cs.total_sales, 
    RANK() OVER (ORDER BY cs.total_sales DESC) AS sales_rank
    FROM customer_sales cs
)
SELECT cr.sales_rank,c.customer_name,cr.total_sales
FROM customer_ranked cr
JOIN  
customers c ON cr.customer_id = c.customer_id
ORDER BY cr.sales_rank;

 * mysql+mysqlconnector://root:***@localhost/Superstore
793 rows affected.

     sales_rank    customer_name total_sales
0             1      Sean Miller    25043.07
1             2     Tamara Chand    19052.22
2             3     Raymond Buch    15117.35
3             4     Tom Ashbrook    14595.62
4             5    Adrian Barton    14473.57
..          ...              ...         ...
788         789       Roy Skaria       22.33
789         790  Mitch Gastineau       16.74
790         791     Carl Jackson       16.52
791         792     Lela Donovan        5.30
792         793    Thais Sissman        4.84

[793 rows x 3 columns]

## Mini Project: Customer Sales Insights

### Q1. Who are the top 5 customers?

In [67]:
%%sql
WITH customer_sales AS (
    SELECT o.customer_id,c.customer_name,ROUND(SUM(o.sales), 2) AS total_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY o.customer_id, c.customer_name
)
SELECT customer_name,total_sales,
RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
FROM customer_sales
ORDER BY sales_rank
LIMIT 5;

 * mysql+mysqlconnector://root:***@localhost/Superstore
5 rows affected.

   customer_name total_sales  sales_rank
0    Sean Miller    25043.07           1
1   Tamara Chand    19052.22           2
2   Raymond Buch    15117.35           3
3   Tom Ashbrook    14595.62           4
4  Adrian Barton    14473.57           5

### Q2. Who are the bottom 5 customers?

In [68]:
%%sql
WITH customer_sales AS (
    SELECT o.customer_id,c.customer_name,
    ROUND(SUM(o.sales), 2) AS total_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY o.customer_id, c.customer_name
)
SELECT customer_name,total_sales,
       RANK() OVER (ORDER BY total_sales ASC) AS sales_rank
FROM customer_sales
ORDER BY sales_rank
LIMIT 5;

 * mysql+mysqlconnector://root:***@localhost/Superstore
5 rows affected.

     customer_name total_sales  sales_rank
0    Thais Sissman        4.84           1
1     Lela Donovan        5.30           2
2     Carl Jackson       16.52           3
3  Mitch Gastineau       16.74           4
4       Roy Skaria       22.33           5

### Q3. Which customers made only one order?

In [69]:
%%sql

SELECT c.customer_name, COUNT(DISTINCT o.order_id) AS total_unique_orders
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY o.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.order_id) = 1;

 * mysql+mysqlconnector://root:***@localhost/Superstore
12 rows affected.

        customer_name  total_unique_orders
0   Anthony O'Donnell                    1
1      Anemone Ratner                    1
2        Carl Jackson                    1
3        Jenna Caffey                    1
4      Jocasta Rupert                    1
5        Lela Donovan                    1
6     Mitch Gastineau                    1
7   Patricia Hirasaki                    1
8     Ricardo Emerson                    1
9       Roland Murray                    1
10  Susan MacKendrick                    1
11      Theresa Coyne                    1

### Q4. Which customers have above-average total sales?

In [70]:
%%sql
WITH customer_sales AS (
    SELECT o.customer_id,c.customer_name,ROUND(SUM(o.sales), 2) AS total_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY o.customer_id, c.customer_name
)
SELECT customer_name,total_sales
FROM customer_sales
WHERE total_sales > (SELECT AVG(total_sales) FROM customer_sales)
ORDER BY total_sales DESC;

 * mysql+mysqlconnector://root:***@localhost/Superstore
294 rows affected.

     customer_name total_sales
0      Sean Miller    25043.07
1     Tamara Chand    19052.22
2     Raymond Buch    15117.35
3     Tom Ashbrook    14595.62
4    Adrian Barton    14473.57
..             ...         ...
289     Julie Kriz     2932.49
290    Shaun Weien     2921.54
291   Maris LaWare     2921.51
292       Rob Dowd     2912.90
293   Craig Yedwab     2900.02

[294 rows x 2 columns]

### Q5. What is the highest order value per customer?

In [71]:
%%sql
WITH order_values AS (
    SELECT customer_id, order_id, SUM(sales) AS order_total
    FROM orders
    GROUP BY customer_id, order_id
)
SELECT c.customer_name, MAX(ov.order_total) AS highest_order_value
FROM order_values ov
JOIN customers c ON ov.customer_id = c.customer_id
GROUP BY ov.customer_id, c.customer_name
ORDER BY highest_order_value DESC;

 * mysql+mysqlconnector://root:***@localhost/Superstore
793 rows affected.

       customer_name highest_order_value
0        Sean Miller            23661.24
1       Tamara Chand            18336.74
2       Raymond Buch            14052.48
3       Tom Ashbrook            13716.46
4       Becky Martin            10539.90
..               ...                 ...
788  Mitch Gastineau               16.74
789     Carl Jackson               16.52
790       Roy Skaria               12.68
791     Lela Donovan                5.30
792    Thais Sissman                2.81

[793 rows x 2 columns]